# Makefile for java tutorial sequence 001-010

.SUFFIXES: .java .class

# make target for 'HelloWorld.java'
helloworld:
	@javac HelloWorld.java;	\
	java HelloWorld;

# clean target that will remove all the compiled .class files
clean:
	$(RM) *.class
